name: Validate

on:
  pull_request:

jobs:
  validate:
    name: Validate Lua Syntax
    runs-on: local-docker
    container: catthehacker/ubuntu:act-latest

    steps:
      - name: Install Lua 5.1
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Lua files
        shell: bash
        run: |
          find . -type f -name "*.lua" \
            -exec sh -c 'echo "Checking $1"; luac5.1 -p "$1"' _ {} \;